---
###################################################
##Author: Almir Candido                            #
##Contact: https://br.linkedin.com/in/almircandido #
##                                                 #
##Ansible Version: 2.9                             #
##                                                 #
##Requisitos:                                      #
##Install:                                         #
##python-boto                                      #
##python-boto3                                     #
##pip install boto3                                #
####################################################
#This playbook creates a file with information about the instances of the chosen region. Works in conjunction with the ec2_list_template.j2 file
- hosts: localhost
  gather_facts: false
  vars:
    aws_access_key: xxxxxxxxxxxxxxxxxxxx #inform access key
    aws_secret_key: xxxxxxxxxxxxxxxxxxxx #inform secret key
    file_path: "/tmp/{{ region }}"
  vars_prompt:
    - name: "region"
      prompt: |
           "Regions                                              
         
              Name                                 Code            
          
              US East (Ohio)                       us-east-2        
              US East (N. Virginia)                us-east-1        
              US West (N. California)              us-west-1       
              US West (Oregon)                     us-west-2       
              Africa (Cape Town)                   af-south-1      
              Asia Pacific (Hong Kong)             ap-east-1       
              Asia Pacific (Mumbai)                ap-south-1      
              Asia Pacific (Osaka-Local)           ap-northeast-3  
              Asia Pacific (Seoul)                 ap-northeast-2  
              Asia Pacific (Singapore)             ap-southeast-1  
              Asia Pacific (Sydney)                ap-southeast-2  
              Asia Pacific (Tokyo)                 ap-northeast-1  
              Canada (Central)                     ca-central-1    
              Europe (Frankfurt)                   eu-central-1    
              Europe (Ireland)                     eu-west-1       
              Europe (London)                      eu-west-2       
              Europe (Milan)                       eu-south-1      
              Europe (Paris)                       eu-west-3       
              Europe (Stockholm)                   eu-north-1      
              Middle East (Bahrain)                me-south-1      
              South America (São Paulo)            sa-east-1
              
            Inform the Region Code:"
      private: no

  tasks:
    - name: All instances for Region "{{ region }}"
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
      tags: all_server
      register: result
    - debug:
        msg: "There is no instance in the chosen region"
      when: (result.instances is not defined) or (result.instances|length == 0)

    - name: Creating file with instance information
      template:
        src: ./ec2_list_template.j2 
        dest: "{{ file_path }}"
      when: (result.instances is defined) and (result.instances|length > 0)

    - debug:
        msg: "Your file has been saved to {{ file_path }}"
      when: (result.instances is defined) and (result.instances|length > 0)
...
